# Generated by Django 2.1.2 on 2018-11-15 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_access_log_access_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='access_log',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Place', verbose_name='local'),
            preserve_default=False,
        ),
    ]
